packages:
  - '.'
  - 'v2-backend'
  - 'proptii-backend'
  - 'proptii-search'

allowBuilds:
  '@firebase/util': true
  '@nestjs/core': true
  '@parcel/watcher': set this to true or false
  '@scarf/scarf': true
  core-js: true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@firebase/util'
  - '@nestjs/core'
  - '@scarf/scarf'
  - core-js
  - esbuild
  - msgpackr-extract
  - protobufjs
  - sharp
  - unrs-resolver
