// ...existing code...
const navigation = [
  // ...existing navigation items...
  {
    name: 'Contracts',
    href: '/contracts',
    icon: DocumentTextIcon,
  },
  // ...existing navigation items...
];
// ...existing code...