// marketing-hub-feature/src/services/recoveryService.ts
import { useCanvasStoreEnhanced } from '../stores/canvasStoreEnhanced';

export interface RecoveryState {
  id: string;
  timestamp: number;
  canvasData: any;
  metadata: {
    objectCount: number;
    lastModified: number;
    version: string;
  };
}

export interface AutoSaveState {
  id: string;
  timestamp: number;
  canvasData: any;
  isAutoGenerated: boolean;
}

export class RecoveryService {
  private static readonly RECOVERY_KEY = 'canvas_recovery_states';
  private static readonly AUTOSAVE_KEY = 'canvas_autosave_states';
  private static readonly MAX_RECOVERY_STATES = 10;
  private static readonly MAX_AUTOSAVE_STATES = 5;
  private static readonly AUTOSAVE_INTERVAL = 30000; // 30 seconds

  private static autosaveTimer: NodeJS.Timeout | null = null;
  private static isAutosaveEnabled = true;

  /**
   * Save current canvas state for recovery
   */
  public static saveRecoveryState(canvasData: any, metadata?: any): RecoveryState {
    const recoveryState: RecoveryState = {
      id: `recovery_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      timestamp: Date.now(),
      canvasData: this.sanitizeCanvasData(canvasData),
      metadata: {
        objectCount: canvasData?.objects?.length || 0,
        lastModified: Date.now(),
        version: '1.0',
        ...metadata
      }
    };

    try {
      const existingStates = this.getRecoveryStates();
      existingStates.unshift(recoveryState); // Add to beginning

      // Keep only the most recent states
      const limitedStates = existingStates.slice(0, this.MAX_RECOVERY_STATES);
      
      localStorage.setItem(this.RECOVERY_KEY, JSON.stringify(limitedStates));
      
      console.log('Recovery state saved:', recoveryState.id);
      return recoveryState;
    } catch (error) {
      console.error('Failed to save recovery state:', error);
      throw error;
    }
  }

  /**
   * Get all available recovery states
   */
  public static getRecoveryStates(): RecoveryState[] {
    try {
      const stored = localStorage.getItem(this.RECOVERY_KEY);
      return stored ? JSON.parse(stored) : [];
    } catch (error) {
      console.error('Failed to get recovery states:', error);
      return [];
    }
  }

  /**
   * Restore canvas from a recovery state
   */
  public static async restoreFromRecovery(recoveryId: string): Promise<boolean> {
    try {
      const recoveryStates = this.getRecoveryStates();
      const recoveryState = recoveryStates.find(state => state.id === recoveryId);
      
      if (!recoveryState) {
        throw new Error('Recovery state not found');
      }

      const canvasStore = useCanvasStoreEnhanced.getState();
      await canvasStore.loadCanvas(recoveryState.canvasData);
      
      console.log('Canvas restored from recovery state:', recoveryId);
      return true;
    } catch (error) {
      console.error('Failed to restore from recovery:', error);
      return false;
    }
  }

  /**
   * Delete a recovery state
   */
  public static deleteRecoveryState(recoveryId: string): boolean {
    try {
      const recoveryStates = this.getRecoveryStates();
      const filteredStates = recoveryStates.filter(state => state.id !== recoveryId);
      
      localStorage.setItem(this.RECOVERY_KEY, JSON.stringify(filteredStates));
      console.log('Recovery state deleted:', recoveryId);
      return true;
    } catch (error) {
      console.error('Failed to delete recovery state:', error);
      return false;
    }
  }

  /**
   * Clear all recovery states
   */
  public static clearAllRecoveryStates(): boolean {
    try {
      localStorage.removeItem(this.RECOVERY_KEY);
      console.log('All recovery states cleared');
      return true;
    } catch (error) {
      console.error('Failed to clear recovery states:', error);
      return false;
    }
  }

  /**
   * Start automatic saving
   */
  public static startAutosave(): void {
    if (this.autosaveTimer) {
      this.stopAutosave();
    }

    this.autosaveTimer = setInterval(() => {
      if (this.isAutosaveEnabled) {
        this.performAutosave();
      }
    }, this.AUTOSAVE_INTERVAL);

    console.log('Autosave started');
  }

  /**
   * Stop automatic saving
   */
  public static stopAutosave(): void {
    if (this.autosaveTimer) {
      clearInterval(this.autosaveTimer);
      this.autosaveTimer = null;
    }
    console.log('Autosave stopped');
  }

  /**
   * Enable/disable autosave
   */
  public static setAutosaveEnabled(enabled: boolean): void {
    this.isAutosaveEnabled = enabled;
    console.log('Autosave', enabled ? 'enabled' : 'disabled');
  }

  /**
   * Perform an autosave
   */
  private static performAutosave(): void {
    try {
      const canvasStore = useCanvasStoreEnhanced.getState();
      const canvasData = {
        objects: canvasStore.objects,
        canvasSettings: canvasStore.canvasSettings,
        timestamp: Date.now()
      };

      const autosaveState: AutoSaveState = {
        id: `autosave_${Date.now()}`,
        timestamp: Date.now(),
        canvasData: this.sanitizeCanvasData(canvasData),
        isAutoGenerated: true
      };

      const existingStates = this.getAutosaveStates();
      existingStates.unshift(autosaveState);
      
      // Keep only the most recent autosave states
      const limitedStates = existingStates.slice(0, this.MAX_AUTOSAVE_STATES);
      
      localStorage.setItem(this.AUTOSAVE_KEY, JSON.stringify(limitedStates));
      
      console.log('Autosave completed:', autosaveState.id);
    } catch (error) {
      console.error('Failed to perform autosave:', error);
    }
  }

  /**
   * Get all autosave states
   */
  public static getAutosaveStates(): AutoSaveState[] {
    try {
      const stored = localStorage.getItem(this.AUTOSAVE_KEY);
      return stored ? JSON.parse(stored) : [];
    } catch (error) {
      console.error('Failed to get autosave states:', error);
      return [];
    }
  }

  /**
   * Restore from the most recent autosave
   */
  public static async restoreFromLatestAutosave(): Promise<boolean> {
    try {
      const autosaveStates = this.getAutosaveStates();
      if (autosaveStates.length === 0) {
        throw new Error('No autosave states available');
      }

      const latestAutosave = autosaveStates[0]; // Most recent is first
      const canvasStore = useCanvasStoreEnhanced.getState();
      await canvasStore.loadCanvas(latestAutosave.canvasData);
      
      console.log('Canvas restored from autosave:', latestAutosave.id);
      return true;
    } catch (error) {
      console.error('Failed to restore from autosave:', error);
      return false;
    }
  }

  /**
   * Export recovery data for backup
   */
  public static exportRecoveryData(): string {
    try {
      const recoveryStates = this.getRecoveryStates();
      const autosaveStates = this.getAutosaveStates();
      
      const exportData = {
        recoveryStates,
        autosaveStates,
        exportTimestamp: new Date().toISOString(),
        version: '1.0'
      };

      return JSON.stringify(exportData, null, 2);
    } catch (error) {
      console.error('Failed to export recovery data:', error);
      throw error;
    }
  }

  /**
   * Import recovery data from backup
   */
  public static importRecoveryData(exportData: string): boolean {
    try {
      const data = JSON.parse(exportData);
      
      if (data.recoveryStates) {
        localStorage.setItem(this.RECOVERY_KEY, JSON.stringify(data.recoveryStates));
      }
      
      if (data.autosaveStates) {
        localStorage.setItem(this.AUTOSAVE_KEY, JSON.stringify(data.autosaveStates));
      }
      
      console.log('Recovery data imported successfully');
      return true;
    } catch (error) {
      console.error('Failed to import recovery data:', error);
      return false;
    }
  }

  /**
   * Sanitize canvas data before storage
   */
  private static sanitizeCanvasData(canvasData: any): any {
    if (!canvasData) return null;

    // Remove sensitive data and ensure data integrity
    const sanitized = {
      ...canvasData,
      // Remove any potential security issues
      objects: canvasData.objects?.map((obj: any) => ({
        ...obj,
        // Ensure objects have required properties
        id: obj.id || `obj_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
        type: obj.type || 'unknown'
      }))
    };

    return sanitized;
  }

  /**
   * Get recovery statistics
   */
  public static getRecoveryStats() {
    const recoveryStates = this.getRecoveryStates();
    const autosaveStates = this.getAutosaveStates();
    
    return {
      recoveryStates: {
        count: recoveryStates.length,
        latest: recoveryStates[0]?.timestamp || null,
        oldest: recoveryStates[recoveryStates.length - 1]?.timestamp || null
      },
      autosaveStates: {
        count: autosaveStates.length,
        latest: autosaveStates[0]?.timestamp || null,
        isEnabled: this.isAutosaveEnabled,
        interval: this.AUTOSAVE_INTERVAL
      }
    };
  }
}

export default RecoveryService;

